name: Check for Code Format Errors
on: [push]
jobs:
  Check-for-Code-Format-Errors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
      - name: Install NPM Packages
        run: yarn install
      - name: Run prettier
        run: yarn prettier
