name: Check for Code Format Errors
on: [push]
jobs:
  Check-for-Code-Format-Errors:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
